name: Marketing Launch Reminder

on:
  push:
    tags:
      - 'v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post launch reminder to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 ReviveForge launch tag pushed! Remember to post on Product Hunt: [PH DRAFT LINK]"
          }' $SLACK_WEBHOOK_URL
